# Generated by Django 5.2.12 on 2026-03-11 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('is_commissioner', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('double', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('triple', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('hr', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('rbi', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('run', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('bb', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('sb', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('cs', models.DecimalField(decimal_places=2, default=-1, max_digits=5)),
                ('hbp', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('so_hitting', models.DecimalField(decimal_places=2, default=-0.5, max_digits=5, verbose_name='SO (hitting)')),
                ('ip_out', models.DecimalField(decimal_places=2, default=1, help_text='Points per out (3 per full IP)', max_digits=5, verbose_name='Per out recorded')),
                ('so_pitching', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='SO (pitching)')),
                ('win', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('loss', models.DecimalField(decimal_places=2, default=-3, max_digits=5)),
                ('save_pts', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Save')),
                ('hold_pts', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Hold')),
                ('er', models.DecimalField(decimal_places=2, default=-1, max_digits=5, verbose_name='ER')),
                ('hit_against', models.DecimalField(decimal_places=2, default=-0.5, max_digits=5, verbose_name='H against')),
                ('bb_pitching', models.DecimalField(decimal_places=2, default=-0.5, max_digits=5, verbose_name='BB (pitching)')),
                ('hr_against', models.DecimalField(decimal_places=2, default=-1, max_digits=5, verbose_name='HR against')),
            ],
            options={
                'verbose_name': 'Point Settings',
                'verbose_name_plural': 'Point Settings',
            },
        ),
        migrations.CreateModel(
            name='RealTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(unique=True)),
                ('start_date', models.DateField(help_text='Monday')),
                ('end_date', models.DateField(help_text='Sunday')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('OF', 'Outfield'), ('DH', 'Designated Hitter'), ('SP', 'Starting Pitcher'), ('RP', 'Relief Pitcher')], max_length=2)),
                ('fantasy_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='league.fantasyteam')),
                ('real_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.realteam')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RealGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='league.realteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='league.realteam')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'home_team', 'away_team')},
            },
        ),
        migrations.CreateModel(
            name='PitchingGameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outs', models.PositiveIntegerField(default=0, help_text='Total outs recorded (IP stored as outs)', verbose_name='Outs')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='H')),
                ('runs', models.PositiveIntegerField(default=0, verbose_name='R')),
                ('er', models.PositiveIntegerField(default=0, verbose_name='ER')),
                ('bb', models.PositiveIntegerField(default=0, verbose_name='BB')),
                ('so', models.PositiveIntegerField(default=0, verbose_name='SO')),
                ('hr', models.PositiveIntegerField(default=0, verbose_name='HR')),
                ('win', models.BooleanField(default=False, verbose_name='W')),
                ('loss', models.BooleanField(default=False, verbose_name='L')),
                ('save', models.BooleanField(default=False, verbose_name='SV')),
                ('hold', models.BooleanField(default=False, verbose_name='HLD')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.fantasyteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_logs', to='league.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_logs', to='league.realgame')),
            ],
            options={
                'ordering': ['-game__date'],
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='HittingGameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.PositiveIntegerField(default=0, verbose_name='AB')),
                ('runs', models.PositiveIntegerField(default=0, verbose_name='R')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='H')),
                ('doubles', models.PositiveIntegerField(default=0, verbose_name='2B')),
                ('triples', models.PositiveIntegerField(default=0, verbose_name='3B')),
                ('hr', models.PositiveIntegerField(default=0, verbose_name='HR')),
                ('rbi', models.PositiveIntegerField(default=0, verbose_name='RBI')),
                ('bb', models.PositiveIntegerField(default=0, verbose_name='BB')),
                ('so', models.PositiveIntegerField(default=0, verbose_name='SO')),
                ('sb', models.PositiveIntegerField(default=0, verbose_name='SB')),
                ('cs', models.PositiveIntegerField(default=0, verbose_name='CS')),
                ('hbp', models.PositiveIntegerField(default=0, verbose_name='HBP')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.fantasyteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitting_logs', to='league.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitting_logs', to='league.realgame')),
            ],
            options={
                'ordering': ['-game__date'],
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_team1', to='league.fantasyteam')),
                ('team_2', models.ForeignKey(blank=True, help_text='Null = bye week', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_team2', to='league.fantasyteam')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='league.week')),
            ],
            options={
                'unique_together': {('week', 'team_1')},
            },
        ),
    ]
