# Generated by Django 5.2.12 on 2026-03-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitchinggamelog',
            old_name='save',
            new_name='save_game',
        ),
    ]
