# Generated by Django 5.2.12 on 2026-03-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_rename_save_pitchinggamelog_save_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='class_year',
            field=models.CharField(blank=True, choices=[('FY', 'First Year'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Grad'), ('N/A', 'N/A')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('IF', 'Infielder'), ('OF', 'Outfield'), ('DH', 'Designated Hitter'), ('SP', 'Starting Pitcher'), ('RP', 'Relief Pitcher')], max_length=10),
        ),
    ]
