# Generated by Django 5.2.12 on 2026-03-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_simplify_positions_rosterslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fantasy_team_since',
            field=models.DateField(blank=True, help_text='Date this player was added to their current fantasy team', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('C', 'Catcher'), ('IF', 'Infield'), ('OF', 'Outfield'), ('P', 'Pitcher')], max_length=10),
        ),
    ]
