# Generated by Django 5.2.12 on 2026-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_player_fantasy_team_since_alter_player_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realgame',
            options={'ordering': ['-date', 'game_number']},
        ),
        migrations.AlterUniqueTogether(
            name='realgame',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='realgame',
            name='game_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 for single game or first game of doubleheader, 2 for second game'),
        ),
        migrations.AlterUniqueTogether(
            name='realgame',
            unique_together={('date', 'home_team', 'away_team', 'game_number')},
        ),
    ]
