# Generated by Django 5.2.12 on 2026-03-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_realgame_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realgame',
            name='source_url',
            field=models.URLField(blank=True, help_text='Box score URL this game was scraped from', max_length=500, null=True, unique=True),
        ),
    ]
