# Generated by Django 5.2.12 on 2026-03-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_activityentry_pendingrequest_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cached_games_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='cached_ppg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='player',
            name='cached_season_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='player',
            name='cached_weekly_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
