# Generated by Django 5.2.12 on 2026-03-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_player_cached_games_played_player_cached_ppg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='user_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='entry_type',
            field=models.CharField(choices=[('add', 'Player Added'), ('drop', 'Player Dropped'), ('dispute_submitted', 'Dispute Submitted'), ('dispute_approved', 'Dispute Approved'), ('dispute_denied', 'Dispute Denied'), ('dispute_cancelled', 'Dispute Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
