# Generated by Django 5.2.12 on 2026-03-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_pendingrequest_user_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
