# Generated by Django 5.2.12 on 2026-03-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_add_display_name_to_fantasy_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchinggamelog',
            name='hold',
        ),
        migrations.RemoveField(
            model_name='pointsettings',
            name='hold_pts',
        ),
        migrations.RemoveField(
            model_name='pointsettings',
            name='hr_against',
        ),
    ]
