# Generated by Django 5.2.12 on 2026-03-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_pendingrequest_missing_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_mode', models.BooleanField(default=True, help_text='Auto-unlock Monday 12:01 AM – 3:29 PM ET; locked all other times.')),
                ('manual_locked', models.BooleanField(default=False, help_text='Used when normal mode is off. True = all teams locked.')),
            ],
            options={
                'verbose_name': 'League Settings',
            },
        ),
    ]
