# Generated by Django 5.2.12 on 2026-03-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_trade_tradeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
