# Generated by Django 5.2.12 on 2026-03-17 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_weeklylineupslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_days', to='league.week')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('week', 'date')},
            },
        ),
    ]
