# Generated by Django 5.2.12 on 2026-03-19 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_excludedday'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsettings',
            name='coach_win',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Coach win'),
        ),
        migrations.AddField(
            model_name='realgame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='league.realteam'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fantasy_team_since', models.DateField(blank=True, null=True)),
                ('cached_season_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cached_weekly_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fantasy_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='league.fantasyteam')),
                ('real_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='league.realteam')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
