# Generated by Django 5.2.12 on 2026-03-19 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_pointsettings_coach_win_realgame_winner_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='league.coach'),
        ),
        migrations.AlterField(
            model_name='pendingrequest',
            name='request_type',
            field=models.CharField(choices=[('game_add', 'Add Game'), ('stat_modify', 'Modify Stats'), ('missing_game', 'Missing Game'), ('coach_win', 'Coach Win')], max_length=20),
        ),
    ]
