# Generated by Django 5.2.12 on 2026-03-19 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_pendingrequest_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='league.coach'),
        ),
    ]
