# Generated by Django 5.2.12 on 2026-03-19 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_transaction_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.coach'),
        ),
    ]
