# Generated by Django 5.2.12 on 2026-03-19 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_activityentry_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitem',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.coach'),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.player'),
        ),
    ]
