# Generated by Django 5.2.12 on 2026-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_tradeitem_coach_alter_tradeitem_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('away_team_name', models.CharField(max_length=150)),
                ('home_team_name', models.CharField(max_length=150)),
                ('game_time', models.CharField(blank=True, default='', max_length=30)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('FINAL', 'Final'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=12)),
                ('source_event_id', models.CharField(max_length=200, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'game_time', 'id'],
            },
        ),
    ]
