# Generated by Django 5.2.12 on 2026-04-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_scheduledgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledgame',
            name='box_score_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
